development: &default
  adapter: mysql2
  user: root
  password:
  database: la_plaza_development
  host: 127.0.0.1
  encoding: utf8

test: &test
  <<: *default
  database: la_plaza_test

production:
  <<: *default  
  database: la_plaza_production
